
cmake_minimum_required(VERSION 3.20)

project(MazeHunter LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(SFML 3 REQUIRED COMPONENTS Graphics Window System)

add_executable(MazeHunter
    src/main.cpp
    src/Player.cpp
)

target_include_directories(MazeHunter PRIVATE include)

target_link_libraries(MazeHunter
    PRIVATE
        SFML::Graphics
        SFML::Window
        SFML::System
)
